squashfs-init to 1.7
Verify overlay rootfs has bash rootfs roothash listed as compatible

Purpose is to avoid mix-match attacks of different rootfs base and overlay versions

diff --git a/recipes-core/squashfs-init/files/init.in b/recipes-core/squashfs-init/files/init.in
--- a/recipes-core/squashfs-init/files/init.in
+++ b/recipes-core/squashfs-init/files/init.in
@@ -84,7 +84,7 @@ mkdir -p /rootfs.dev || die "Failed creating mount directories"
 mount -o ro "$srcdev" /rootfs.dev || die "Failed mounting $srcdev"
 
 # Enable dm-verity mapping for rootfs integrity
-container-util @ROOTFS_PUBLIC_KEY@ --open rootfs.0 /rootfs.dev/boot/rootfs.squashfs || die "Failed enabling dm-verity"
+roothash_0="$(container-util @ROOTFS_PUBLIC_KEY@ --open rootfs.0 /rootfs.dev/boot/rootfs.squashfs)" || die "Failed enabling dm-verity"
 
 # Mount squash
 mkdir -p /rootfs.0 || die "Failed creating squash mountpoint"
@@ -94,12 +94,25 @@ mount -t squashfs -o ro /dev/mapper/rootfs.0 /rootfs.0 || die "Failed mounting s
 # file /rootfs.dev/boot/rootfs.squashfs.1 is available.
 # On error the additional rootfs is silently dropped.
 if [ -f /rootfs.dev/boot/rootfs.squashfs.1 ]; then
-	if container-util @ROOTFS_PUBLIC_KEY@ --open rootfs.1 /rootfs.dev/boot/rootfs.squashfs.1; then
+	roothash_1="$(container-util @ROOTFS_PUBLIC_KEY@ --open rootfs.1 /rootfs.dev/boot/rootfs.squashfs.1)"
+	if [ $? -eq 0 ]; then
+		echo "Found squashfs.1"
 		mkdir -p /rootfs.1 || die "Failed creating squashfs.1 mountpoint"
 		if mount -t squashfs -o ro /dev/mapper/rootfs.1 /rootfs.1; then
-			lower_extra="/rootfs.1:"
+			# Verify the additional image has the roothash of rootfs.0 available
+			# in /rootfs.1/boot/roothash.compatible
+			if [ "$roothash_0" = "$(cat /rootfs.1/boot/roothash.compatible)" ]; then
+				echo "Verified squashfs.1"
+				lower_extra="/rootfs.1:"
+			else
+				umount /rootfs.1 || die "Failed unmounting squasfs.1"
+				rmdir /rootfs.1 || die "Failed removing squashfs.1 mountpoint"
+				veritysetup close rootfs.1 || die "Failed closing squashfs.1 verity"
+				roothash_1=""
+			fi
 		else
 			rmdir /rootfs.1 || die "Failed removing squashfs.1 mountpoint"
+			veritysetup close rootfs.1 || die "Failed closing squashfs.1 verity"
 		fi
 	fi
 fi
